### PR TITLE
Bumping version in spec file to 1.2.1-0.1.beta

### PR DESCRIPTION
**Pull request by dkliban**

### CODE REVIEW

**Comment by mhrivnak** [comment]
The travis failures appear unrelated to this change.

**Comment by mhrivnak** [comment]
Looks like the travis failures will be fixed by this PR: https://github.com/pulp/crane/pull/48

**Comment by rbarlow** [comment]
@dkliban is this PR still needed since we are going to try to release 2.0 with pulp 2.8?

**Comment by dkliban** [comment]
it is not needed.

**Pull request closed without merging**
